# Generated by Django 2.1.4 on 2018-12-22 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year', models.IntegerField(default=0)),
                ('date', models.CharField(max_length=100, verbose_name='date of release')),
                ('age', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('time', models.IntegerField()),
                ('director', models.CharField(max_length=100)),
                ('pos', models.IntegerField()),
                ('neg', models.IntegerField()),
                ('image', models.FileField(upload_to='')),
            ],
        ),
    ]
