# Generated by Django 2.1.4 on 2018-12-22 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='categories',
            field=models.CharField(default='others', max_length=255),
        ),
        migrations.AddField(
            model_name='film',
            name='large_title',
            field=models.TextField(default=121),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='film',
            name='small_title',
            field=models.TextField(default=12121),
            preserve_default=False,
        ),
    ]
